"""create rates table

Revision ID: 19c283c87f3d
Revises: 
Create Date: 2025-05-21 15:24:35.555449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19c283c87f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ust_rub_cents', sa.Integer(), nullable=False),
    sa.Column('cny_rub_fens', sa.Integer(), nullable=False),
    sa.Column('ust_rub_plus1_cents', sa.Integer(), nullable=False),
    sa.Column('cny_rub_plus2p_fens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.drop_table('rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ust_rub', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cny_rub', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date', name='rates_pkey')
    )
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
