"""create rates table

Revision ID: 31208e7daede
Revises: 19c283c87f3d
Create Date: 2025-05-21 16:03:27.759915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31208e7daede'
down_revision: Union[str, None] = '19c283c87f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ust_rub_cents', sa.Integer(), nullable=False),
    sa.Column('cny_rub_fens', sa.Integer(), nullable=False),
    sa.Column('ust_rub_plus1_cents', sa.Integer(), nullable=False),
    sa.Column('cny_rub_plus2p_fens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.drop_table('currency_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ust_rub_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cny_rub_fens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ust_rub_plus1_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cny_rub_plus2p_fens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='currency_rates_pkey'),
    sa.UniqueConstraint('date', name='currency_rates_date_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('rates')
    # ### end Alembic commands ###
